services:
  web:
    build: .
    container_name: talker
    environment:
      - DB_SERVER=db
      - DB_USER=root
      - DB_PASSWORD=12345678
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=talker
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
    ports:
      - "3006:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: